# Generated by Django 2.2 on 2020-05-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_auto_20200518_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='date',
            new_name='release_date',
        ),
    ]
